server:
  port: 8089
  contextPath: /
---
spring:
  profiles: default
datasource:
  buslinespoa:
    url: jdbc:h2:~/buslines
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 3
    hibernate:
      #hbm2ddl.method: update
      hbm2ddl.method: create-drop
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
